using SadConsole;
using Microsoft.Xna.Framework;
using SadConsole.Game;
using SadConsole.Consoles;
using System;
using System.Collections.Generic;

namespace roguelike.Consoles
{
    public class MapConsole : SadConsole.Consoles.Console
    {
        GameObject playerEntity;

        RogueSharp.FieldOfView rogueFOV;
        public GameObject Player { get { return playerEntity; } }
        MapObjects.MapObjectBase[,] mapData;
        RogueSharp.Map rogueMap;
        IReadOnlyCollection<RogueSharp.Cell> previousFOV = new List<RogueSharp.Cell>();

        public MapConsole(int viewWidth, int viewHeight, int mapWidth, int mapHeight): base(mapWidth, mapHeight)
        {
            TextSurface.RenderArea = new Rectangle(0, 0, viewWidth, viewHeight);

            AnimatedTextSurface playerAnimation = new AnimatedTextSurface("default", 1, 1, Engine.DefaultFont);
            playerAnimation.CreateFrame();
            playerAnimation.CurrentFrame[0].Foreground = Color.Orange;
            playerAnimation.CurrentFrame[0].GlyphIndex = '@';

            playerEntity = new GameObject(Engine.DefaultFont);
            playerEntity.Animation = playerAnimation;

            playerEntity.Position = new Point(0, 0);

            GenerateMap();
        }

        public override void Render()
        {
            base.Render();
            playerEntity.Render();
        }
        public override void Update()
        {
            base.Update();
            playerEntity.Update();
        }

        public void MovePlayerBy(Point amount)
        {
            // Get the position the player will be at
            Point newPosition = playerEntity.Position + amount;

            // Check to see if the position is within the map
            if (new Rectangle(0, 6, Width, Height).Contains(newPosition) && rogueMap.IsWalkable(newPosition.X, newPosition.Y))
            {
                // Move the player
                playerEntity.Position += amount;

                // Scroll the view area to center the player on the screen
                TextSurface.RenderArea = new Rectangle(playerEntity.Position.X - (TextSurface.RenderArea.Width / 2),
                                                        playerEntity.Position.Y - (TextSurface.RenderArea.Height / 2),
                                                        TextSurface.RenderArea.Width, TextSurface.RenderArea.Height);

                // If he view area moved, we'll keep our entity in sync with it.
                playerEntity.RenderOffset = this.Position - TextSurface.RenderArea.Location;

                // Erase status on old FOV
                foreach (var cell in previousFOV)
                    mapData[cell.X, cell.Y].RemoveCellFromView(this[cell.X, cell.Y]);

                // Calculate the new FOV
                previousFOV = rogueFOV.ComputeFov(playerEntity.Position.X, playerEntity.Position.Y, 10, true);

                // Set status on new FOV
                foreach (var cell in previousFOV)
                {
                    rogueMap.SetCellProperties(cell.X, cell.Y, cell.IsTransparent, cell.IsWalkable, true);
                    mapData[cell.X, cell.Y].RenderToCell(this[cell.X, cell.Y], true, rogueMap.GetCell(cell.X, cell.Y).IsExplored);
                }
            }
        }

        private void GenerateMap()
        {
            // Create the map
            RogueSharp.MapCreation.IMapCreationStrategy<RogueSharp.Map> mapCreationStrategy
                = new RogueSharp.MapCreation.RandomRoomsMapCreationStrategy<RogueSharp.Map>(Width, Height, 100, 20, 7);

            rogueMap = RogueSharp.Map.Create(mapCreationStrategy);
            rogueFOV = new RogueSharp.FieldOfView(rogueMap);
            mapData = new MapObjects.MapObjectBase[Width, Height];
            // Loop through the map information generated by RogueSharp and create our cached visuals of that data
            foreach (var cell in rogueMap.GetAllCells())
            {
                if (cell.IsWalkable)
                {
                    // Our local information about each map square
                    mapData[cell.X, cell.Y] = new MapObjects.Floor();

                    // Copy the appearance we've defined for Floor or Wall or whatever, to the actual console data that is rendered
                    mapData[cell.X, cell.Y].RenderToCell(this[cell.X, cell.Y], false, false);
                }
                else
                {
                    rogueMap.SetCellProperties(cell.X, cell.Y, false, false);
                    mapData[cell.X, cell.Y] = new MapObjects.Wall();
                    mapData[cell.X, cell.Y].RenderToCell(this[cell.X, cell.Y], false, false);

                    // We're a wall, so we block LOS
                    rogueMap.SetCellProperties(cell.X, cell.Y, false, cell.IsWalkable);
                }
            }

            RogueSharp.Random.IRandom random = new RogueSharp.Random.DotNetRandom();

            // Position the player somewhere on a walkable square
            while (true)
            {
                int x = random.Next(Width - 1);
                int y = random.Next(Height - 1);
                // Add appropriate fix to avoid putting player in inventory bar
                if (y > 5  && rogueMap.IsWalkable(x, y))
                {
                    playerEntity.Position = new Point(x, y);

                    // TODO: fix possitioning code
                    TextSurface.RenderArea = new Rectangle(playerEntity.Position.X - (TextSurface.RenderArea.Width / 2),
                                                            playerEntity.Position.Y - (TextSurface.RenderArea.Height / 2),
                                                            TextSurface.RenderArea.Width, TextSurface.RenderArea.Height);

                    playerEntity.RenderOffset = Position - TextSurface.RenderArea.Location;
                    MovePlayerBy(new Point(0, 0));
                    break;
                }
            }
        }
    }
}
